# Generated by Django 5.2.1 on 2025-05-28 02:05

import carga_tct.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('guia', models.CharField(max_length=50, verbose_name='Guía')),
                ('patente', models.CharField(max_length=10, verbose_name='Patente')),
                ('estacion_servicio', models.CharField(max_length=100, verbose_name='Estación de Servicio')),
                ('suministro', models.CharField(max_length=50, verbose_name='Suministro')),
                ('kilometraje', models.IntegerField(verbose_name='KMS')),
                ('consumo_litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo [Lt]')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=carga_tct.models.get_image_upload_path, verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Combustible',
                'verbose_name_plural': 'Registros de Combustible',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
